In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris


In [3]:
# Logistic Regression on Digits Dataset
iris=load_iris()
my_df=pd.DataFrame(iris.data,columns=iris.feature_names)
my_df['target']=iris.target
my_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [21]:
print("image Data shape",iris.data.shape)
print("label Data shape",iris.target.shape)

image Data shape (150, 4)
label Data shape (150,)


In [70]:
feature_names = iris.feature_names
target_names = iris.target_names
print("Feature names:", feature_names)
print("Target names:", target_names)
print("\nFirst 10 rows of X:\n", X[:10])


Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']

First 10 rows of X:
 [[165, 19], [175, 32], [136, 35], [174, 65], [141, 28], [176, 15], [131, 32], [166, 6], [128, 32], [179, 10]]


In [74]:
import numpy as np
from sklearn import preprocessing

Input_data = np.array([[2.1, -1.9, 5.5],
                       [-1.5, 2.4, 3.5],
                       [0.5, -7.9, 5.6],
                       [5.9, 2.3, -5.8]])

# Displaying the mean and the standard deviation of the input data
mean_data = np.mean(Input_data, axis=0)
std_data = np.std(Input_data, axis=0)

print("Mean of the Input Data:", mean_data)
print("Standard Deviation of the Input Data:", std_data)


Mean of the Input Data: [ 1.75  -1.275  2.2  ]
Standard Deviation of the Input Data: [2.71431391 4.20022321 4.69414529]


In [76]:
data_normalized_l1 = preprocessing.normalize(Input_data, norm='l1')

print("\nL1 normalized data:\n", data_normalized_l1)



L1 normalized data:
 [[ 0.22105263 -0.2         0.57894737]
 [-0.2027027   0.32432432  0.47297297]
 [ 0.03571429 -0.56428571  0.4       ]
 [ 0.42142857  0.16428571 -0.41428571]]


In [77]:
data_normalized_l2 = preprocessing.normalize(Input_data, norm='l2')

print("\nL2 normalized data:\n", data_normalized_l2)



L2 normalized data:
 [[ 0.33946114 -0.30713151  0.88906489]
 [-0.33325106  0.53320169  0.7775858 ]
 [ 0.05156558 -0.81473612  0.57753446]
 [ 0.68706914  0.26784051 -0.6754239 ]]


In [23]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.25, random_state=0)


In [24]:
from sklearn.linear_model import LogisticRegression


In [25]:
logisticRegr = LogisticRegression()


In [26]:
logisticRegr.fit(x_train, y_train)


C:\Users\Krunal\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [27]:
logisticRegr.predict(x_test[0].reshape(1,-1))


array([2])

In [28]:
logisticRegr.predict(x_test[0:10])


array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1])

In [29]:
predictions = logisticRegr.predict(x_test)


In [30]:
score = logisticRegr.score(x_test, y_test)
print(score)


0.9736842105263158


In [6]:
from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit([[0, 0], [1, 1], [2, 2]], [0, 1, 2])
reg.coef_

array([0.5, 0.5])

In [9]:
reg.intercept_

0.1363636363636364

In [14]:
from sklearn import linear_model
reg = linear_model.Lasso(alpha=0.1)
reg.fit([[0, 0], [1, 1]], [0, 1])
reg.predict([[1, 1]])

array([0.8])

In [15]:
from sklearn import linear_model
X = [[0., 0.], [1., 1.], [2., 2.], [3., 3.]]
Y = [0., 1., 2., 3.]
reg = linear_model.BayesianRidge()
reg.fit(X, Y)

BayesianRidge()

In [16]:
reg.predict([[1, 0.]])

array([0.50000013])

In [17]:
reg.coef_

array([0.49999993, 0.49999993])

In [18]:
from sklearn.linear_model import TweedieRegressor
reg = TweedieRegressor(power=1, alpha=0.5, link='log')
reg.fit([[0, 0], [0, 1], [2, 2]], [0, 1, 2])
reg.coef_
reg.intercept_

-0.7638091359123443

In [19]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np
X = np.arange(6).reshape(3, 2)
X
poly = PolynomialFeatures(degree=2)
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [20]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
import numpy as np
model = Pipeline([('poly', PolynomialFeatures(degree=3)),
                  ('linear', LinearRegression(fit_intercept=False))])
x = np.arange(5)
y = 3 - 2 * x + x ** 2 - x ** 3
model = model.fit(x[:, np.newaxis], y)
model.named_steps['linear'].coef_

array([ 3., -2.,  1., -1.])

In [40]:
#logostic regression
from sklearn import datasets
from sklearn import linear_model
from sklearn.datasets import load_iris
X, y = load_iris(return_X_y = True)
LRG = linear_model.LogisticRegression(random_state=0, solver='liblinear', multi_class='auto')
LRG.fit(X, y)
LRG.score(X, y)


0.96

In [44]:
#linear regression
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
import numpy as np

X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y = np.dot(X, np.array([1, 2])) + 3

scaler = StandardScaler()
X_standardized = scaler.fit_transform(X)

regr = LinearRegression(fit_intercept=True, n_jobs=2)
regr.fit(X_standardized, y)

prediction = regr.predict(np.array([[3, 5]]))

print("Coefficients:", regr.coef_)
print("Intercept:", regr.intercept_)
print("Prediction:", prediction)


Coefficients: [0.5        1.41421356]
Intercept: 8.5
Prediction: [17.07106781]


In [45]:
#Ridge Regression
from sklearn.linear_model import Ridge
import numpy as np
n_samples, n_features = 15, 10
rng = np.random.RandomState(0)
y = rng.randn(n_samples)
X = rng.randn(n_samples, n_features)
rdg = Ridge(alpha = 0.5)
rdg.fit(X, y)
rdg.score(X,y)


0.7629498741931637

In [46]:
#lasso model
from sklearn import linear_model
Lreg = linear_model.Lasso(alpha = 0.5)
Lreg.fit([[0,0], [1, 1], [2, 2]], [0, 1, 2])


Lasso(alpha=0.5)

In [47]:
Lreg.predict([[0,1]])


array([0.75])

In [48]:
Lreg.coef_


array([0.25, 0.  ])

In [51]:
Lreg.intercept_


0.75

In [52]:
Lreg.n_iter_


2

In [53]:
#polynomial futures

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
import numpy as np

Stream_model = Pipeline([('poly', PolynomialFeatures(degree=3)), ('linear', LinearRegression(fit_intercept=False))])

x = np.arange(5)
y = 3 - 2 * x + x ** 2 - x ** 3
Stream_model.fit(x[:, np.newaxis], y)

coefficients = Stream_model.named_steps['linear'].coef_

print("Polynomial Coefficients:", coefficients)


Polynomial Coefficients: [ 3. -2.  1. -1.]


In [55]:
#super vector machine
import numpy as np
X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]])
y = np.array([1, 1, 2, 2])
from sklearn.svm import SVC
SVCClf = SVC(kernel = 'linear',gamma = 'scale', shrinking = False,)
SVCClf.fit(X, y)


SVC(kernel='linear', shrinking=False)

In [56]:
SVCClf.coef_


array([[0.5, 0.5]])

In [57]:
SVCClf.predict([[-0.5,-0.8]])


array([1])

In [58]:
SVCClf.n_support_


array([1, 1])

In [59]:
SVCClf.support_vectors_


array([[-1., -1.],
       [ 1.,  1.]])

In [60]:
SVCClf.support_


array([0, 2])

In [61]:
SVCClf.intercept_


array([-0.])

In [62]:
SVCClf.fit_status_


0

In [64]:
#knn
from sklearn.neighbors import NearestNeighbors

nrst_neigh = NearestNeighbors(n_neighbors=3, algorithm='ball_tree')
nrst_neigh.fit(Input_data)

distances, indices = nrst_neigh.kneighbors(Input_data)

# Print the indices and distances
print("Indices:", indices)
print("Distances:", distances)


Indices: [[0 1 3]
 [1 2 0]
 [2 1 0]
 [3 4 0]
 [4 5 3]
 [5 6 4]
 [6 5 4]]
Distances: [[0.         1.41421356 2.23606798]
 [0.         1.41421356 1.41421356]
 [0.         1.41421356 2.82842712]
 [0.         1.41421356 2.23606798]
 [0.         1.41421356 1.41421356]
 [0.         1.41421356 1.41421356]
 [0.         1.41421356 2.82842712]]


In [65]:
# Import necessary libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

# Load breast cancer dataset
data = load_iris()
label_names = data['target_names']
labels = data['target']
feature_names = data['feature_names']
features = data['data']

# Print information about the dataset
print(label_names)
print(labels[0])
print(feature_names[0])
print(features[0])

# Split the dataset into training and testing sets
train, test, train_labels, test_labels = train_test_split(
    features, labels, test_size=0.40, random_state=42
)

# Create a Gaussian Naive Bayes classifier and fit the model
GNBclf = GaussianNB()
model = GNBclf.fit(train, train_labels)

# Make predictions on the test set
preds = GNBclf.predict(test)

# Print the predictions
print(preds)


['setosa' 'versicolor' 'virginica']
0
sepal length (cm)
[5.1 3.5 1.4 0.2]
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 2 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0 1 1 2 1 2 1 2 1 0 2 1 0 0 0 1]


In [66]:
#decision tree
from sklearn import tree
from sklearn.model_selection import train_test_split

X = [[165, 19], [175, 32], [136, 35], [174, 65], [141, 28], [176, 15],
     [131, 32], [166, 6], [128, 32], [179, 10], [136, 34], [186, 2], [126, 25],
     [176, 28], [112, 38], [169, 9], [171, 36], [116, 25], [196, 25], [196, 38],
     [126, 40], [197, 20], [150, 25], [140, 32], [136, 35]]

Y = ['Man', 'Woman', 'Woman', 'Man', 'Woman', 'Man', 'Woman', 'Man', 'Woman',
     'Man', 'Woman', 'Man', 'Woman', 'Woman', 'Woman', 'Man', 'Woman', 'Woman',
     'Man', 'Woman', 'Woman', 'Man', 'Man', 'Woman', 'Woman']

data_feature_names = ['height', 'length of hair']

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=1)

DTclf = tree.DecisionTreeClassifier()
DTclf = DTclf.fit(X_train, y_train)  # Use X_train and y_train for fitting

prediction = DTclf.predict([[135, 29]])
print(prediction)


['Woman']


In [67]:
prediction = DTclf.predict_proba([[135,29]])
print(prediction)


[[0. 1.]]
